# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 810de44829674fe31a83f50ff6b09765a39203e03ccdd4d6bd8511d7decdb08dd7d73a82375fbbb62a6c466bd52805cceaa8cd3f877ddfb79660a0ff6ce55a64

test:
  secret_key_base: 887c3c53a0740633438ad508f25d3b2d357592851bd463eb6dbbc0b173221152f846ce63905071efa0ed51f9a0c201efd0c6eaa02c69d1402c039b2a52f2aeb0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
